name: Playwright Pytest App

on:
  push:
    branches:
      - main

jobs:
  run_tests_and_publish_report:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Important for Allure history to work correctly

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install

    - name: Install Allure command-line
      run: npm install -g allure-commandline

    - name: Run tests
      run: |
        pytest -m smoke

    - name: Publish JUnit Test Report
      uses: mikepenz/action-junit-report@v5
      if: always()
      with:
        report_paths: '**/junit_reports/report.xml'

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: Pytest report & Logs
        path: |
          pytest_reports/
          logs/
        overwrite: true
        if-no-files-found: error

    - name: Load Allure history
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages-branch

    - name: Build Allure Report
      uses: simple-elf/allure-report-action@v1.8
      id: allure-report
      if: always()
      with:
        allure_results: allure-results
        gh_pages: gh-pages-branch
        allure_report: allure-report
        allure_history: allure-history

    - name: Deploy Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-report


