name: Playwright Pytest App

on:
  push:
    branches:
      - main

jobs:
  run_tests_and_publish_report:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write
      repository-projects: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Important for Allure history to work correctly

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install

    - name: Run tests
      run: |
        pytest -m smoke_
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v5
      if: success() || failure()
      with:
        report_paths: '**/build/junit_reports/report.xml'
